### ISSUE TITLE
What do you mean by 'no expressive return type'?

### ISSUE THREAD

**Issue by kozross** [sordina/churros#5] opened 2020-10-15 04:16 UTC
In the README, you state the following as a disadvantage of this library:

> No expressive return type encoded in the Churro datatype...

What do you mean by 'expressive return type' here?

**Comment by sordina** [comment] 2020-10-15 06:27
Hi @kozross ,

What this refers to is although the input/outputs of the processes that are transported are tracked in the type, the actual result of the background process is currently (). There's no reason why this couldn't be something actually useful.

The current datatype is:

```haskell
data Churro t i o   = Churro { runChurro :: IO (t (Maybe i), t (Maybe o), Async ()) }
```

Imagine that the datatype was:

```haskell
data Churro a t i o   = Churro { runChurro :: IO (t (Maybe i), t (Maybe o), Async a) }
```

You could then write Churros like:

```haskell
sinkList :: Transport t => Churro [i] t i Void
sinkList = buildChurro \i _o -> yankList i
```

Which would be cool since then you're tracking the result of the async computation doing something useful. Currently this same outcome is achieved with a custom run function, which, while practical, isn't as elegant.

I think it should actually be possible to do this, but the instances don't fall out as easily as they do when it's just `()`.

**Comment by kozross** [comment] 2020-10-15 06:28
What particular instances become awkward or impossible in the non-`()` formulation?

**Comment by sordina** [comment] 2020-10-15 06:35
I've clarified here: bd2117b..98e1579

let me know if you want further info!

**Comment by sordina** [comment] 2020-10-15 06:49
I didn't invest much time into trying, but `Category` stumped me when I gave it a go:

```haskell
data Churro t i o   = Churro { runChurro :: IO (t (Maybe i), t (Maybe o), Async ()) }
instance Transport t => Category (Churro t) where ...
```

vs.

```haskell
data Churro a t i o   = Churro { runChurro :: IO (t (Maybe i), t (Maybe o), Async a) }
instance Transport t => Category (Churro a t) where ...
```

This implies that both Churros must return an `a` from their async action. Obviously we actually want something more like 

```haskell
instance Transport t => Category' (Churro a t) (Churro b t) where ...
   -- implementation that returns `b`s.
```

but then this isn't a standard category.

One easy out that works for `sinkList` is

```haskell
data Churro t i o   = Churro { runChurro :: IO (t (Maybe i), t (Maybe o), Async [o]) }
```

that says you can return a list of items of the same type as your output (or alternatively input) type, but that is a big kludge and not worth it for just satisfying this one scenario.

If you know a neat way to achieve the category instance I'd be very happy!

**Comment by sordina** [comment] 2020-10-16 08:32
@kozross I found a not-terrible compramise in this fashion: #7

**Comment by sordina** [comment] 2020-10-16 08:34
https://github.com/sordina/churros/pull/7/files#diff-e1391d6c5deb1c343f9212d849a1d1e98292c94f24ab9a6bd28016c75770ccd8R168

**Comment by kozross** [comment] 2020-10-16 09:44
I was going to suggest that it might work if we have `Monoid a` - I believe `Category` at least is doable in that case.

**Comment by sordina** [comment] 2020-10-16 13:27
I had a go with the Monoid idea and while it does indeed work, the issue is that both Churros `a`s have to be the same Monoid, yet aren't combined monadically - so the restriction is a bit too strong unless your entire categorically composed pipeline components coincidentally return the same types. It's still more flexible than `()` so an improvement to a lot of the functions, but I feel it doesn't really achieve the outcome I'd hope for. Not that I have any better suggestions!

**Comment by kozross** [comment] 2020-10-16 17:14
Yeah, but I think it's more or less an increase in flexibility 'for free'. In fact, both of your prior examples (with list and unit) are just special cases.

**Comment by sordina** [comment] 2020-10-16 21:20
True, I'll adopt it!

**Comment by sordina** [comment] 2020-10-16 22:46
Merged PR.

**Closed as completed by sordina** 2020-10-16 22:46 UTC
